### ISSUE TITLE
请问有计划开源退火开始前的base模型吗？

### ISSUE THREAD

**Issue by jyweky** [bilibili/Index-1.9B#18]
请问有计划开源退火开始前的base模型吗？
我想在 WSD 的退火阶段追加下游高质量数据和定制的SFT数据。
如果连同退火阶段的预训练数据也开源就更好了（用来混合定制数据一起退火）🙏

**Comment by asirgogogo** [comment]
已开源退火前的base模型：https://huggingface.co/IndexTeam/Index-1.9B-Constant-LR

**Comment by jyweky** [comment]
非常感谢🎉
