### ISSUE TITLE
RAG好像并没有被真正的应用到？

### ISSUE THREAD

**Issue by GoEnthusiast** [bilibili/Index-1.9B#19]
大神您好，我是一名刚开始接触大模型的新手，正在学习RAG，所以我认真阅读了您位于roleplay文件夹中的index_play.py和realtime_chat.py的代码。我有一点疑惑想请教一下
self.generate_with_question(self.history)
self.create_datasets()
这两行代码好像最终仅仅只是完成了character中的文件生成？因为当我注释掉这两行代码，仅仅只使用"三三_测试问题.json"这个文件也是可以跑通后续代码的。接下来
json_data = load_json(f"{self.save_samples_dir}/{self.role_name}_测试问题.json")
这段代码读取的文件内容，看起来好像只是加了部分聊天话术的普通prompt？？
再之后就是
inputs = tokenizer(text, return_tensors="pt")
outputs = model.generate(**inputs, repetition_penalty=1.1, max_length=2048)
这两行代码与模型进行交流，我打印了text，我发现它就是"_测试问题.json"中的内容。
我是否可以理解为，该模型的使用，其实并非真正的应用到了RAG技术，而是通过prompt模版的形式，生成带有部分聊天话术的prompt去与模型进行交互？？

**Comment by GoEnthusiast** [comment]
可能是我对RAG理解的问题，这与我想象中的RAG有点不太一样😂。问题问的有点唐突，大神别介意哈，我现在确实有点蒙圈儿

**Comment by lingyun-gao** [comment]
可以参考下aws对于RAG的解释：https://aws.amazon.com/cn/what-is/retrieval-augmented-generation/

RAG技术从外部数据检索到相关信息，并注入prompt，用以增强用户的输入。在角色扮演中，用户每次输入，代码都会从语料库中找到相关的历史对话，并拼入prompt。

我们这里只是把prompt的结果写入了文件，这两行代码的作用就是这个。
```
self.generate_with_question(self.history)
self.create_datasets()
```

如果注释掉了，是可以运行，但是每次的输入就都不会更新了

**Comment by GoEnthusiast** [comment]
> 可以参考下aws对于RAG的解释：https://aws.amazon.com/cn/what-is/retrieval-augmented-generation/
> 
> RAG技术从外部数据检索到相关信息，并注入prompt，用以增强用户的输入。在角色扮演中，用户每次输入，代码都会从语料库中找到相关的历史对话，并拼入prompt。
> 
> 我们这里只是把prompt的结果写入了文件，这两行代码的作用就是这个。
> 
> ```
> self.generate_with_question(self.history)
> self.create_datasets()
> ```
> 
> 如果注释掉了，是可以运行，但是每次的输入就都不会更新了

好的，非常感谢

**Comment by lingyun-gao** [comment]
已解决
