### ISSUE TITLE
关于 GGUF 格式的 Index-1.9B-Character

### ISSUE THREAD

**Issue by mili-tan** [bilibili/Index-1.9B#21]
各位好，
我注意到 Index-1.9B-Chat 有提供 GGUF 格式，
Index-1.9B-Character 能否也同样提供 GGUF 呢？

另外感谢各位的工作。

**Comment by liuyang135** [comment]
我们已经在准备了，马上会提供。
敬请关注，感谢支持。

**Comment by zyhsuperman** [comment]
你好，我们现在已经提供了character模型gguf的版本。
感谢支持。
