### ISSUE TITLE
 ImportError: cannot import name 'IndexForCausalLM' from 'transformers'

### ISSUE THREAD

**Issue by mst272** [bilibili/Index-1.9B#24]
from transformers import AutoTokenizer, IndexForCausalLM

> ImportError: cannot import name 'IndexForCausalLM' from 'transformers'

我看到模型的modeling_index.py文件中写了可以这样导入的示例（822行），但是为什么会报错啊
 ```python
  >>> from transformers import AutoTokenizer, IndexForCausalLM
    
  | >>> model = IndexForCausalLM.from_pretrained(PATH_TO_CONVERTED_WEIGHTS)
  | >>> tokenizer = AutoTokenizer.from_pretrained(PATH_TO_CONVERTED_TOKENIZER)
  |  
  | >>> prompt = "Hey, are you conscious? Can you talk to me?"
  | >>> inputs = tokenizer(prompt, return_tensors="pt")
  |  
  | >>> # Generate
  | >>> generate_ids = model.generate(inputs.input_ids, max_length=30)
  | >>> tokenizer.batch_decode(generate_ids, skip_special_tokens=True, clean_up_tokenization_spaces=False)[0]
  | "Hey, are you conscious? Can you talk to me?\nI'm not conscious, but I can talk to you."
  | ```"""


`

**Comment by asirgogogo** [comment]
很抱歉，IndexForCausalLM类方法 目前还没有加入到 transformers 的包里面。

正确的调用方法是

from transformers import AutoTokenizer, AutoModelForCausalLM

解释：AutoModelForCausalLM会自动解析模型config中的auto_map字段，将AutoModelForCausalLM映射到modeling_index.py文件中的IndexForCausalLM类

**Comment by mst272** [comment]
> 很抱歉，IndexForCausalLM类方法 目前还没有加入到 transformers 的包里面。
> 
> 正确的调用方法是
> 
> from transformers import AutoTokenizer, AutoModelForCausalLM
> 
> 解释：AutoModelForCausalLM会自动解析模型config中的auto_map字段，将AutoModelForCausalLM映射到modeling_index.py文件中的IndexForCausalLM类

感谢回答，但是还有一个问题，看到index是有ForSequenceClassification方法的，但是使用AutoModelForSequenceClassification加载时会报错，请问该如何使用index的ForSequenceClassification方法呢？

**Comment by asirgogogo** [comment]
我们更新了huggingface上的config.json文件，你可以在更新文件后，通过以下命令进行加载

from transformers import AutoTokenizer, AutoModelForCausalLM, AutoModelForSequenceClassification
