### ISSUE TITLE
roleplay有辦法與TavernAI集成或提供openai compatible API嗎?

### ISSUE THREAD

**Issue by k0286** [bilibili/Index-1.9B#25]
我想嘗試將Index-1.9B-Character作為SillyTavern / TavernAI的backend。

似乎沒辦法直接透過`roleplay`目前提供的互動方式接入。

**Comment by lingyun-gao** [comment]
@k0286 已提供openai compatible API
参考：https://github.com/bilibili/Index-1.9B/pull/26
