### ISSUE TITLE
A problem about multi-gpu inferencing?

### ISSUE THREAD

**Issue by lclichen** [bilibili/Index-1.9B#3]
Here is the error when i run `python hf_based_demo.py` and submit some text to the chatbox:
`RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1!`

![image](https://github.com/bilibili/Index-1.9B/assets/14357890/b2bde0c7-e06c-4568-968f-81c1239954db)

**Comment by lclichen** [comment]
Is this a normal state? I have a env with pytorch=2.0.1+cu117.

**Comment by lclichen** [comment]
And here is a full screenshot of the reported error.
![image](https://github.com/bilibili/Index-1.9B/assets/14357890/94cde387-a6d7-45af-bbeb-6c0c0634fa6c)

**Comment by asirgogogo** [comment]
You can try to set os.environ['CUDA_VISIBLE_DEVICES'] = '0' and os.environ['CUDA_VISIBLE_DEVICES'] = '1' in different programs.
